#!/usr/bin/env python3
"""Create a tiny REINVENT4 data-pipeline fixture and matching config.

The generated dataset intentionally contains valid molecules, duplicates,
invalid syntax, a salt/fragment, stereochemistry, an unexpected element, and an
unwanted charged halogen token so agents can practice validation and triage
before running ``reinvent_datapre`` on real data.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys


ROWS = [
    ("ethanol", "CCO", "valid but may fail min_heavy_atoms/min_carbons if thresholds are strict"),
    ("aspirin_a", "CC(=O)Oc1ccccc1C(=O)O", "valid representative molecule"),
    ("aspirin_b", "CC(=O)Oc1ccccc1C(=O)O", "duplicate final SMILES"),
    ("bad_syntax", "not_a_smiles", "invalid SMILES-like text"),
    ("salt_fragment", "CCO.Cl", "largest-fragment and element/filter behavior"),
    ("alanine_stereo", "C[C@@H](N)C(=O)O", "stereochemistry handling"),
    ("unexpected_silicon", "c1ccc([SiH3])cc1", "requires adding Si to filter.elements if intended"),
    ("charged_halogen", "CC(=O)O[Cl+][O-]", "rejected by unwanted charged halogen token filter"),
]

SEPARATORS = {"tab": "\t", "comma": ",", "semicolon": ";"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Write a tiny CSV/SMI fixture plus data_pipeline.toml for REINVENT4 reinvent_datapre smoke checks.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--out-dir", type=Path, default=Path("data_pipeline_fixture"), help="Output directory to create.")
    parser.add_argument("--format", choices=("csv", "smi"), default="csv", help="Fixture input format.")
    parser.add_argument("--separator", choices=tuple(SEPARATORS), default="tab", help="Delimiter for the fixture input.")
    parser.add_argument("--smiles-column", default="SMILES", help="SMILES column name for CSV configs.")
    parser.add_argument("--output-name", default="processed.smi", help="Configured output SMILES filename.")
    parser.add_argument(
        "--allow-silicon",
        action="store_true",
        help="Include Si in filter.elements so the silicon row can pass element screening if RDKit cleanup allows it.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing fixture files in the output directory.",
    )
    return parser.parse_args()


def toml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t") + '"'


def write_csv_fixture(path: Path, separator: str, smiles_column: str) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter=separator)
        writer.writerow([smiles_column, "Name", "Comment"])
        for name, smiles, comment in ROWS:
            writer.writerow([smiles, name, comment])


def write_smi_fixture(path: Path, separator: str) -> None:
    del separator  # .smi smoke fixtures stay one-column for the data-pipeline reader.
    with path.open("w", encoding="utf-8", newline="") as handle:
        for _name, smiles, _comment in ROWS:
            handle.write(smiles + "\n")


def build_config(input_name: str, separator: str, smiles_column: str, output_name: str, allow_silicon: bool) -> str:
    elements = ["C", "N", "O", "S", "F", "Cl", "Br", "I"]
    if allow_silicon:
        elements.append("Si")
    element_list = ", ".join(toml_quote(element) for element in elements)
    return f"""# Tiny REINVENT4 data-pipeline smoke config generated by make_tiny_smiles_fixture.py
input_csv_file = {toml_quote(input_name)}
smiles_column = {toml_quote(smiles_column)}
separator = {toml_quote(separator)}
output_smiles_file = {toml_quote(output_name)}
num_procs = 1
chunk_size = 10

[filter]
elements = [{element_list}]
transforms = ["standard"]
min_heavy_atoms = 2
max_heavy_atoms = 90
max_mol_weight = 1200.0
min_carbons = 1
max_num_rings = 12
max_ring_size = 7
keep_stereo = true
keep_isotope_molecules = true
uncharge = true
canonical_tautomer = false
kekulize = false
randomize_smiles = false
report_errors = true
inchi_key_deduplicate = false
"""


def assert_can_write(path: Path, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"refusing to overwrite existing file without --force: {path}")


def main() -> int:
    args = parse_args()
    separator = SEPARATORS[args.separator]
    out_dir = args.out_dir.expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)

    input_name = "tiny_smiles.csv" if args.format == "csv" else "tiny_smiles.smi"
    input_path = out_dir / input_name
    config_path = out_dir / "data_pipeline.toml"
    output_path = out_dir / args.output_name

    try:
        assert_can_write(input_path, args.force)
        assert_can_write(config_path, args.force)
        if output_path.exists() and not args.force:
            raise FileExistsError(f"configured output already exists; remove it or pass --force: {output_path}")
    except FileExistsError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    if args.format == "csv":
        write_csv_fixture(input_path, separator, args.smiles_column)
    else:
        write_smi_fixture(input_path, separator)

    config_text = build_config(
        input_name=input_name,
        separator=separator,
        smiles_column=args.smiles_column,
        output_name=args.output_name,
        allow_silicon=args.allow_silicon,
    )
    config_path.write_text(config_text, encoding="utf-8")

    print(f"Wrote fixture input: {input_path}")
    print(f"Wrote config: {config_path}")
    print(f"Configured output: {output_path}")
    print("Validate with:")
    print(f"  python validate_data_pipeline_config.py {config_path} --sample-rows 20")
    print("Run preprocessing from the fixture directory with:")
    print(f"  cd {out_dir} && reinvent_datapre data_pipeline.toml --log-filename data_pipeline.log")
    return 0


if __name__ == "__main__":
    sys.exit(main())
