#!/usr/bin/env python3
"""Write a safe Chai-1 run_inference Python script template.

This helper does not import chai_lab and does not run inference. It only writes a
configurable script that a user can review and run in an environment where
chai_lab is installed and a suitable CUDA device is available.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from textwrap import dedent


def _path_expr(value: str | None) -> str:
    if value is None:
        return "None"
    return f"Path({value!r})"


def _string_expr(value: str | None) -> str:
    if value is None:
        return "None"
    return repr(value)


def build_template(args: argparse.Namespace) -> str:
    clean_comment = (
        "This script removes OUTPUT_DIR before inference because CLEAN_OUTPUT_DIR is True."
        if args.clean_output_dir
        else "This script refuses to run if OUTPUT_DIR already contains files."
    )

    return dedent(
        f'''
        #!/usr/bin/env python3
        """Run Chai-1 inference from a reviewed, explicit configuration.

        Generated by the chai-lab cli-inference helper. {clean_comment}
        Chai-1 inference is intended for a Linux Python 3.10+ environment with a
        CUDA GPU that supports bfloat16. Running this script may download model
        assets unless CHAI_DOWNLOADS_DIR points at an existing cache.
        """

        from __future__ import annotations

        import logging
        import shutil
        from pathlib import Path

        from chai_lab.chai1 import run_inference

        logging.basicConfig(level=logging.INFO)

        FASTA_FILE = Path({str(args.fasta)!r})
        OUTPUT_DIR = Path({str(args.output_dir)!r})
        CLEAN_OUTPUT_DIR = {args.clean_output_dir!r}

        CONFIG = dict(
            use_esm_embeddings={args.use_esm_embeddings!r},
            use_msa_server={args.use_msa_server!r},
            msa_server_url={args.msa_server_url!r},
            msa_directory={_path_expr(args.msa_directory)},
            constraint_path={_path_expr(args.constraint_path)},
            use_templates_server={args.use_templates_server!r},
            template_hits_path={_path_expr(args.template_hits_path)},
            recycle_msa_subsample={args.recycle_msa_subsample!r},
            num_trunk_recycles={args.num_trunk_recycles!r},
            num_diffn_timesteps={args.num_diffn_timesteps!r},
            num_diffn_samples={args.num_diffn_samples!r},
            num_trunk_samples={args.num_trunk_samples!r},
            seed={args.seed!r},
            device={_string_expr(args.device)},
            low_memory={args.low_memory!r},
            fasta_names_as_cif_chains={args.fasta_names_as_cif_chains!r},
        )


        def prepare_output_dir(output_dir: Path, *, clean: bool) -> None:
            if output_dir.exists() and any(output_dir.iterdir()):
                if clean:
                    logging.warning("Removing non-empty output directory: %s", output_dir)
                    shutil.rmtree(output_dir)
                else:
                    raise SystemExit(
                        f"Refusing to overwrite non-empty output directory: {{output_dir}}. "
                        "Choose a new directory or set CLEAN_OUTPUT_DIR = True after review."
                    )
            output_dir.mkdir(parents=True, exist_ok=True)


        def main() -> None:
            if not FASTA_FILE.is_file():
                raise SystemExit(f"FASTA file does not exist: {{FASTA_FILE}}")

            prepare_output_dir(OUTPUT_DIR, clean=CLEAN_OUTPUT_DIR)
            candidates = run_inference(
                fasta_file=FASTA_FILE,
                output_dir=OUTPUT_DIR,
                **CONFIG,
            )

            print("Generated CIF files:")
            for index, cif_path in enumerate(candidates.cif_paths):
                score = candidates.ranking_data[index].aggregate_score.item()
                print(f"  {{index}}: {{cif_path}} score={{score:.4f}}")

            sorted_candidates = candidates.sorted()
            print(f"Best CIF: {{sorted_candidates.cif_paths[0]}}")
            if candidates.msa_coverage_plot_path is not None:
                print(f"MSA coverage plot: {{candidates.msa_coverage_plot_path}}")


        if __name__ == "__main__":
            main()
        '''
    ).lstrip()


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be greater than zero")
    return parsed


def nonnegative_int(value: str) -> int:
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("must be zero or greater")
    return parsed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Write a safe Python template for chai_lab.chai1.run_inference. "
            "The helper itself does not run inference."
        )
    )
    parser.add_argument("--fasta", required=True, help="Input Chai FASTA path to place in the generated script.")
    parser.add_argument("--output-dir", required=True, help="Inference output directory to place in the generated script.")
    parser.add_argument("--script-out", required=True, help="Where to write the generated Python script.")

    parser.add_argument("--device", default="cuda:0", help="Torch device string for inference, usually cuda:0.")
    parser.add_argument("--seed", type=int, default=None, help="Optional random seed.")
    parser.add_argument("--num-trunk-recycles", type=nonnegative_int, default=3, help="Trunk recycle count.")
    parser.add_argument("--num-diffn-timesteps", type=positive_int, default=200, help="Diffusion denoising steps.")
    parser.add_argument("--num-diffn-samples", type=positive_int, default=5, help="Candidate structures per trunk sample.")
    parser.add_argument("--num-trunk-samples", type=positive_int, default=1, help="Independent trunk samples.")
    parser.add_argument("--recycle-msa-subsample", type=nonnegative_int, default=0, help="Optional MSA subsampling recycle value.")

    parser.add_argument("--use-esm-embeddings", dest="use_esm_embeddings", action="store_true", default=True, help="Use ESM embeddings in the generated script; enabled by default.")
    parser.add_argument("--no-use-esm-embeddings", dest="use_esm_embeddings", action="store_false", help="Disable ESM embeddings in the generated script.")
    parser.add_argument("--use-msa-server", action="store_true", help="Enable server-backed MSA generation in the generated script.")
    parser.add_argument("--msa-server-url", default="https://api.colabfold.com", help="MSA server URL when --use-msa-server is used.")
    parser.add_argument("--msa-directory", default=None, help="Prepared local MSA directory to place in the generated script.")
    parser.add_argument("--use-templates-server", action="store_true", help="Enable server-backed template search in the generated script.")
    parser.add_argument("--template-hits-path", default=None, help="Local template hits .m8 path to place in the generated script.")
    parser.add_argument("--constraint-path", default=None, help="Restraints CSV path to place in the generated script.")

    parser.add_argument("--low-memory", dest="low_memory", action="store_true", default=True, help="Use Chai's low-memory mode; enabled by default.")
    parser.add_argument("--no-low-memory", dest="low_memory", action="store_false", help="Disable low-memory mode in the generated script.")
    parser.add_argument("--fasta-names-as-cif-chains", action="store_true", help="Use FASTA entity names as output CIF chain names.")
    parser.add_argument("--clean-output-dir", action="store_true", help="Generated script will delete a non-empty output directory before inference.")
    return parser


def validate_args(args: argparse.Namespace) -> None:
    if args.use_msa_server and args.msa_directory:
        raise SystemExit("Choose either --use-msa-server or --msa-directory, not both.")
    if args.use_templates_server and args.template_hits_path:
        raise SystemExit("Choose either --use-templates-server or --template-hits-path, not both.")


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    validate_args(args)

    script_out = Path(args.script_out)
    script_out.parent.mkdir(parents=True, exist_ok=True)
    script_out.write_text(build_template(args))
    script_out.chmod(0o755)
    print(f"Wrote Chai inference template: {script_out}")


if __name__ == "__main__":
    main()
